## Note:
# This code was generated by https://app.quicktype.io/ and slightly modified.
# This is to be used with the full json request.
# Simply casts the json to classes for typehinting and easier access.
from dataclasses import dataclass
from typing import Optional, Any, List, Union, TypeVar, Type, cast, Callable


T = TypeVar("T")


def from_int(x: Any) -> int:
    assert isinstance(x, int) and not isinstance(x, bool)
    return x


def from_none(x: Any) -> Any:
    assert x is None
    return x


def from_union(fs, x):
    for f in fs:
        try:
            return f(x)
        except:
            pass
    assert False


def to_class(c: Type[T], x: Any) -> dict:
    assert isinstance(x, c)
    return cast(Any, x).to_dict()


def from_str(x: Any) -> str:
    assert isinstance(x, str)
    return x


def from_bool(x: Any) -> bool:
    assert isinstance(x, bool)
    return x


def from_list(f: Callable[[Any], T], x: Any) -> List[T]:
    assert isinstance(x, list)
    return [f(y) for y in x]


def from_float(x: Any) -> float:
    assert isinstance(x, (float, int)) and not isinstance(x, bool)
    return float(x)


def to_float(x: Any) -> float:
    assert isinstance(x, float)
    return x


@dataclass
class Region:
    start: Optional[int] = None
    end: Optional[int] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Region':
        assert isinstance(obj, dict)
        start = from_union([from_int, from_none], obj.get("start"))
        end = from_union([from_int, from_none], obj.get("end"))
        return Region(start, end)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.start is not None:
            result["start"] = from_union([from_int, from_none], self.start)
        if self.end is not None:
            result["end"] = from_union([from_int, from_none], self.end)
        return result


@dataclass
class Date:
    eu: Optional[Region] = None
    na: Optional[Region] = None
    asia: Optional[Region] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Date':
        assert isinstance(obj, dict)
        eu = from_union([Region.from_dict, from_none], obj.get("eu"))
        na = from_union([Region.from_dict, from_none], obj.get("na"))
        asia = from_union([Region.from_dict, from_none], obj.get("asia"))
        return Date(eu, na, asia)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.eu is not None:
            result["eu"] = from_union([lambda x: to_class(Region, x), from_none], self.eu)
        if self.na is not None:
            result["na"] = from_union([lambda x: to_class(Region, x), from_none], self.na)
        if self.asia is not None:
            result["asia"] = from_union([lambda x: to_class(Region, x), from_none], self.asia)
        return result


@dataclass
class UprateItem:
    id: Optional[int] = None
    name: Optional[str] = None

    @staticmethod
    def from_dict(obj: Any) -> 'UprateItem':
        assert isinstance(obj, dict)
        id = from_union([from_int, from_none], obj.get("id"))
        name = from_union([from_str, from_none], obj.get("name"))
        return UprateItem(id, name)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.id is not None:
            result["id"] = from_union([from_int, from_none], self.id)
        if self.name is not None:
            result["name"] = from_union([from_str, from_none], self.name)
        return result


@dataclass
class Banner:
    name: Optional[str] = None
    image: Optional[str] = None
    current: Optional[bool] = None
    uprate_5: Optional[List[Union[UprateItem, str]]] = None
    uprate_4: Optional[List[Union[UprateItem, str]]] = None
    date: Optional[Date] = None
    version: Optional[float] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Banner':
        assert isinstance(obj, dict)
        name = from_union([from_str, from_none], obj.get("name"))
        image = from_union([from_str, from_none], obj.get("image"))
        current = from_union([from_bool, from_none], obj.get("current"))
        uprate_5 = from_union([lambda x: from_list(lambda x: from_union([UprateItem.from_dict, from_str], x), x), from_none], obj.get("uprate_5"))
        uprate_4 = from_union([lambda x: from_list(lambda x: from_union([UprateItem.from_dict, from_str], x), x), from_none], obj.get("uprate_4"))
        date = from_union([Date.from_dict, from_none], obj.get("date"))
        version = from_union([from_float, from_none], obj.get("version"))
        return Banner(name, image, current, uprate_5, uprate_4, date, version)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.name is not None:
            result["name"] = from_union([from_str, from_none], self.name)
        if self.image is not None:
            result["image"] = from_union([from_str, from_none], self.image)
        if self.current is not None:
            result["current"] = from_union([from_bool, from_none], self.current)
        if self.uprate_5 is not None:
            result["uprate_5"] = from_union([lambda x: from_list(lambda x: from_union([lambda x: to_class(UprateItem, x), from_str], x), x), from_none], self.uprate_5)
        if self.uprate_4 is not None:
            result["uprate_4"] = from_union([lambda x: from_list(lambda x: from_union([lambda x: to_class(UprateItem, x), from_str], x), x), from_none], self.uprate_4)
        if self.date is not None:
            result["date"] = from_union([lambda x: to_class(Date, x), from_none], self.date)
        if self.version is not None:
            result["version"] = from_union([to_float, from_none], self.version)
        return result


@dataclass
class StarrailBanners:
    permanent: Optional[List[Banner]] = None
    character: Optional[List[Banner]] = None
    lightcone: Optional[List[Banner]] = None

    @staticmethod
    def from_dict(obj: Any) -> 'StarrailBanners':
        assert isinstance(obj, dict)
        permanent = from_union([lambda x: from_list(Banner.from_dict, x), from_none], obj.get("permanent"))
        character = from_union([lambda x: from_list(Banner.from_dict, x), from_none], obj.get("character"))
        lightcone = from_union([lambda x: from_list(Banner.from_dict, x), from_none], obj.get("lightcone"))
        return StarrailBanners(permanent, character, lightcone)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.permanent is not None:
            result["permanent"] = from_union([lambda x: from_list(lambda x: to_class(Banner, x), x), from_none], self.permanent)
        if self.character is not None:
            result["character"] = from_union([lambda x: from_list(lambda x: to_class(Banner, x), x), from_none], self.character)
        if self.lightcone is not None:
            result["lightcone"] = from_union([lambda x: from_list(lambda x: to_class(Banner, x), x), from_none], self.lightcone)
        return result


@dataclass
class GenshinBanners:
    permanent: Optional[List[Banner]] = None
    character: Optional[List[Banner]] = None
    weapon: Optional[List[Banner]] = None

    @staticmethod
    def from_dict(obj: Any) -> 'GenshinBanners':
        assert isinstance(obj, dict)
        permanent = from_union([lambda x: from_list(Banner.from_dict, x), from_none], obj.get("permanent"))
        character = from_union([lambda x: from_list(Banner.from_dict, x), from_none], obj.get("character"))
        weapon = from_union([lambda x: from_list(Banner.from_dict, x), from_none], obj.get("weapon"))
        return GenshinBanners(permanent, character, weapon)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.permanent is not None:
            result["permanent"] = from_union([lambda x: from_list(lambda x: to_class(Banner, x), x), from_none], self.permanent)
        if self.character is not None:
            result["character"] = from_union([lambda x: from_list(lambda x: to_class(Banner, x), x), from_none], self.character)
        if self.weapon is not None:
            result["weapon"] = from_union([lambda x: from_list(lambda x: to_class(Banner, x), x), from_none], self.weapon)
        return result


def starrail_banners_from_dict(s: Any) -> StarrailBanners:
    return StarrailBanners.from_dict(s)


def starrail_banners_to_dict(x: StarrailBanners) -> Any:
    return to_class(StarrailBanners, x)


def genshin_banners_from_dict(s: Any) -> GenshinBanners:
    return GenshinBanners.from_dict(s)


def genshin_banners_to_dict(x: GenshinBanners) -> Any:
    return to_class(GenshinBanners, x)
