## Note:
# This code was generated by https://app.quicktype.io/ and slightly modified.
# This is to be used with the full json request.
# Simply casts the json to classes for typehinting and easier access.

from dataclasses import dataclass
from typing import Optional, Any, List, TypeVar, Type, cast, Callable
from datetime import datetime

T = TypeVar("T")


def from_int(x: Any) -> int:
    assert isinstance(x, int) and not isinstance(x, bool)
    return x


def from_none(x: Any) -> Any:
    assert x is None
    return x


def from_union(fs, x):
    for f in fs:
        try:
            return f(x)
        except:
            pass
    assert False


def to_class(c: Type[T], x: Any) -> dict:
    assert isinstance(x, c)
    return cast(Any, x).to_dict()


def from_str(x: Any) -> str:
    assert isinstance(x, str)
    return x


def from_list(f: Callable[[Any], T], x: Any) -> List[T]:
    assert isinstance(x, list)
    return [f(y) for y in x]


@dataclass
class Region:
    start: Optional[datetime | int] = None
    end: Optional[datetime | int] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Region':
        assert isinstance(obj, dict)
        start = from_union([from_int, from_none], obj.get("start"))
        end = from_union([from_int, from_none], obj.get("end"))
        return convert_to_datetime(Region(start, end))

    def to_dict(self) -> dict:
        result: dict = {}
        if self.start is not None:
            result["start"] = from_union([from_int, from_none], self.start.timestamp())
        if self.end is not None:
            result["end"] = from_union([from_int, from_none], self.end.timestamp())
        return result


def convert_to_datetime(region: Region) -> Region:
    if region.start is not None:
        region.start = datetime.fromtimestamp(region.start)
    if region.end is not None:
        region.end = datetime.fromtimestamp(region.end)
    return region


def convert_from_datetime(region: Region) -> Region:
    if region.start is not None:
        region.start = int(datetime.timestamp(region.start))
    if region.end is not None:
        region.end = int(datetime.timestamp(region.end))
    return region


@dataclass
class Date:
    eu: Optional[Region] = None
    na: Optional[Region] = None
    asia: Optional[Region] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Date':
        assert isinstance(obj, dict)
        eu = from_union([Region.from_dict, from_none], obj.get("eu"))
        na = from_union([Region.from_dict, from_none], obj.get("na"))
        asia = from_union([Region.from_dict, from_none], obj.get("asia"))
        return Date(eu, na, asia)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.eu is not None:
            result["eu"] = from_union([lambda x: to_class(Region, x), from_none], self.eu)
        if self.na is not None:
            result["na"] = from_union([lambda x: to_class(Region, x), from_none], self.na)
        if self.asia is not None:
            result["asia"] = from_union([lambda x: to_class(Region, x), from_none], self.asia)
        return result


@dataclass
class Banner:
    name: Optional[str] = None
    image: Optional[str] = None
    uprate_5: Optional[List[str]] = None
    uprate_4: Optional[List[str]] = None
    date: Optional[Date] = None

    @staticmethod
    def from_dict(obj: Any) -> 'Banner':
        assert isinstance(obj, dict)
        name = from_union([from_str, from_none], obj.get("name"))
        image = from_union([from_none, from_str], obj.get("image"))
        uprate_5 = from_union([lambda x: from_list(from_str, x), from_none], obj.get("uprate_5"))
        uprate_4 = from_union([lambda x: from_list(from_str, x), from_none], obj.get("uprate_4"))
        date = from_union([Date.from_dict, from_none], obj.get("date"))
        return Banner(name, image, uprate_5, uprate_4, date)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.name is not None:
            result["name"] = from_union([from_str, from_none], self.name)
        if self.image is not None:
            result["image"] = from_union([from_none, from_str], self.image)
        if self.uprate_5 is not None:
            result["uprate_5"] = from_union([lambda x: from_list(from_str, x), from_none], self.uprate_5)
        if self.uprate_4 is not None:
            result["uprate_4"] = from_union([lambda x: from_list(from_str, x), from_none], self.uprate_4)
        if self.date is not None:
            result["date"] = from_union([lambda x: to_class(Date, x), from_none], self.date)
        return result


@dataclass
class GenshinBanner:
    type: Optional[str] = None
    banners: Optional[List[Banner]] = None

    @staticmethod
    def from_dict(obj: Any) -> 'GenshinBanner':
        assert isinstance(obj, dict)
        type = from_union([from_str, from_none], obj.get("type"))
        banners = from_union([lambda x: from_list(Banner.from_dict, x), from_none], obj.get("banners"))
        return GenshinBanner(type, banners)

    def to_dict(self) -> dict:
        result: dict = {}
        if self.type is not None:
            result["type"] = from_union([from_str, from_none], self.type)
        if self.banners is not None:
            result["banners"] = from_union([lambda x: from_list(lambda x: to_class(Banner, x), x), from_none],
                                           self.banners)
        return result


def genshin_banners_from_dict(s: Any) -> List[GenshinBanner]:
    return from_list(GenshinBanner.from_dict, s)


def genshin_banners_to_dict(x: List[GenshinBanner]) -> Any:
    return from_list(lambda x: to_class(GenshinBanner, x), x)
